app:
  # logfile path
  log-file: /var/log/deepflow/app.log
  # loglevel: "debug/info/warn/error"
  log-level: info
  # app http listenport
  listen-port: 20418
  # http request/response timeout
  http_request_timeout: 600
  http_response_timeout: 600
  worker_numbers: 10

  querier:
    host: deepflow-server
    port: 20416
    timeout: 60
  
  controller:
    host: deepflow-server
    port: 20417
    timeout: 60
  
  spec:
    l7_tracing_limit: 1000
    max_iteration: 30
    network_delay_us: 1000000
    allow_multiple_trace_ids_in_tracing_result: false
    call_apm_api_to_supplement_trace: false
