app:
  # logfile path
  log-file: /var/log/deepflow/app.log
  # loglevel: "debug/info/warn/error"
  log-level: info
  # app http listenport
  listen-port: 20418
  # http request/response timeout
  http_request_timeout: 600
  http_response_timeout: 600
  worker_numbers: 10

  querier:
    host: deepflow-server
    port: 20416
    timeout: 60
  
  controller:
    host: deepflow-server
    port: 20417
    timeout: 60
  
  spec:
    # query trace data limit, default: 1000
    l7_tracing_limit: 1000
    # query trace data iteration limit, default: 30
    max_iteration: 30
    # network transport delay tolerance in same host, default: 50000, unit: us
    network_delay_us: 50000
    # host clock sync offset tolerance, default: 10000, unit: us
    host_clock_offset_us: 10000
    # display multiple trace_id trace data in one result, default: false
    allow_multiple_trace_ids_in_tracing_result: false
    # use external apm data to fill trace data, default: false
    call_apm_api_to_supplement_trace: false
    # allow DNS protocol distributed tracing base on DNS transaction-id, default: true
    # known issue when true:
    # due to transaction-id reused, it may leads to big data query and causes query performance issue
    # it also possibly leads to unwanted tracing results
    allow_dns_tracing: true
    # allow extra_trace_ids for trace_id query in iterations, default: true
    allow_extra_trace_ids: true
