app:
  # logfile path
  log-file: /var/log/deepflow/app.log
  # loglevel: "debug/info/warn/error"
  log-level: info
  # app http listenport
  listen-port: 20418
  # http request/response timeout
  http_request_timeout: 600
  http_response_timeout: 600

  querier:
    host: deepflow-server
    port: 20416
    timeout: 60
  
  controller:
    host: deepflow-server
    port: 20417
    timeout: 60
  
  spec:
    l7_tracing_limit: 100
    network_delay_us: 1000000