app:
  # logfile path
  log-file: /var/log/deepflow/app.log
  # loglevel: "debug/info/warn/error"
  log-level: info
  # app http listenport
  listen-port: 20418
  # http request/response timeout
  http_request_timeout: 600
  http_response_timeout: 600
  worker_numbers: 10

  querier:
    host: deepflow-server
    port: 20416
    timeout: 60
  
  controller:
    host: deepflow-server
    port: 20417
    timeout: 60
  
  spec:
    # query trace data limit, default: 1000
    l7_tracing_limit: 1000
    # query trace data iteration limit, default: 30
    max_iteration: 30
    # network transport delay tolerance in same host, default: 50000, unit: us
    network_delay_us: 50000
    # host clock sync offset tolerance, default: 10000, unit: us
    host_clock_offset_us: 10000
    # allow find more trace_id by eBPF or Packet tracing fields, not by trace_ids, default: false
    allow_multiple_trace_ids_in_tracing_result: false
    # use external apm data to fill trace data, default: false
    call_apm_api_to_supplement_trace: false
    # source data for tracing, default: [trace_id, syscall, tcp_seq, x_request_id] (equals to empty)
    # available options: [trace_id, syscall, tcp_seq, x_request_id, dns]
    # each source means one of tracing method enabled
    #   trace_id: global seq through requests
    #   syscall: eBPF tracing through process/threads
    #   tcp_seq: network layer tracing through TCP seq
    #   x_request_id: application layer tracing through X-Request-ID/http header
    #   dns: DNS protocol tracing through DNS transaction-id (request_id), IT'S DEFAULT CLOSE, HAS TO BE OPENED EXPLICITLY
    tracing_source: []
    # when use trace_id/_trace_id_2 iteration to find more trace_ids, we should try our best to find more trace_ids
    # such request with the same trace_id may hold within a long time, like 5 or more minutes.
    # but we should not query those data globally due to performance issue.
    # so, we limit time_range for each time try to find trace_ids.
    # we will to try search data in [now-range, now+range], unit:s, default: 180s
    multiple_trace_iteration_time_range: 180