# 构建层
FROM alpine:3.20.3 AS builder

RUN apk update && apk upgrade
RUN apk add --update --no-cache gcc python3-dev postgresql-dev mysql-client make shadow py3-configobj py3-pip py3-setuptools python3
RUN pip install --upgrade --no-cache-dir --disable-pip-version-check --break-system-package pip

# 设置root密码
RUN echo 'root:deepflow' | chpasswd

# 创建用户 deepflow，ID 为 1000
RUN useradd -u 1000 -m deepflow -s /bin/bash

# Base 构建层
FROM builder AS builder-base
RUN pip install --upgrade --no-cache-dir --disable-pip-version-check --break-system-package cffi

# 自定义构建层
FROM builder-base AS builder-custom
RUN pip install --upgrade --no-cache-dir --user --disable-pip-version-check --break-system-package \
         --no-cache-dir \
         aiofiles==23.2.1 aiohttp==3.10.2 aiosignal==1.3.1 async-timeout==4.0.3 attrs==23.1.0 \
         Deprecated==1.2.14 frozenlist==1.4.0 html5tagger==1.3.0 httptools==0.6.1 \
         idna==3.7 importlib-metadata==6.8.0 multidict==6.0.4 numpy==1.24.4 \
         opentelemetry-api==1.21.0 opentelemetry-sdk==1.21.0 opentelemetry-semantic-conventions==0.42b0 \
         pandas==2.0.3 python-dateutil==2.8.2 pytz==2023.3.post1 PyYAML==6.0.1 \
         sanic==23.6.0 sanic-routing==23.6.0 schematics==2.1.1 six==1.16.0 \
         tracerite==1.1.1 typing_extensions==4.8.0 tzdata==2023.3 \
         ujson==5.8.0 uvloop==0.19.0 websockets==12.0 wrapt==1.16.0 \
         yarl==1.9.2 zipp==3.19.2
RUN chown -R deepflow:deepflow /usr/local/lib/python3.8/

FROM scratch

COPY --from=builder-custom /root/.local /
