# 构建层
FROM python:3.8-slim-bookworm AS builder
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install --no-install-suggests \
    --no-install-recommends --yes \
    gcc \
    libpython3-dev \
    libpq-dev \
    default-libmysqlclient-dev \
    make \
    && \
    pip install --upgrade pip

# Base 构建层
# FROM builder AS builder-base
# RUN pip install cffi 

# 自定义构建层
FROM builder AS builder-custom
RUN pip install --user  --disable-pip-version-check \
     	 --no-cache-dir \
          aiofiles==23.2.1 aiohttp==3.9.5 aiosignal==1.3.1 async-timeout==4.0.3 attrs==23.1.0 \
          Deprecated==1.2.14 frozenlist==1.4.0 html5tagger==1.3.0 httptools==0.6.1 \
          idna==3.7 importlib-metadata==6.8.0 multidict==6.0.4 numpy==1.24.4 \
          opentelemetry-api==1.21.0 opentelemetry-sdk==1.21.0 opentelemetry-semantic-conventions==0.42b0 \
          pandas==2.0.3 python-dateutil==2.8.2 pytz==2023.3.post1 PyYAML==6.0.1 \
          sanic==23.6.0 sanic-routing==23.6.0 schematics==2.1.1 six==1.16.0 \
          tracerite==1.1.1 typing_extensions==4.8.0 tzdata==2023.3 \
          ujson==5.8.0 uvloop==0.19.0 websockets==12.0 wrapt==1.16.0 \
          yarl==1.9.2 zipp==3.17.0 cffi==1.16.0 pyroscope-io==0.7.1 opentelemetry-exporter-otlp-proto-http==1.21.0
FROM scratch
COPY --from=builder-custom /root/.local /

